### ISSUE TITLE
someoneOnBoard()

### ISSUE THREAD

**Issue by heba-aamer** [RCRS-ADF/RCRS-ADF#1]
The method someoneOnBoard() in class AgentInfo is dealing with civilians only. So it does not allow  for rescuing other agents. Moreover it keeps rescuing the agent if it is dead as well.

**Comment by tkmnet** [comment]
> The method someoneOnBoard() in class AgentInfo is dealing with civilians only. 

I think it is no problem. Because AmubulanceTeam is able to load(carry) civilians only.

> So it does not allow for rescuing other agents. 

ActionRescue is able to specify Human class.

> Moreover it keeps rescuing the agent if it is dead as well.

Temporary, We added modified ActionTransport as ActionTransport2 to sample.
However, I do not know whether to use ActionTransport2 at the competition in this year.
